theme: jekyll-theme-minimal
title: ADA Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Dataset
    url: dataset
  - title: Methods
    url: methods
  - title: Results
    url: results
  - title: Interactive Demo
    url: demo
